### ISSUE TITLE
Applications

### ISSUE THREAD

**Issue by 11mLLM** [11mLLM/Prompt-Engineering-Guide#24]
[1차 리뷰 결과물](https://github.com/11mLLM/11mLLM/issues/3) << Click !

## ☑️ Checklist

1. 의미 왜곡이 없으며 원문의 핵심을 포착했는가?
2. 맞춤법과 문법을 준수하는가?
3. 일관성있는 어조인가?
4. 문맥적 오류가 있는가?
5. 합의한 용어를 준수하는가?

**Comment by 11mLLM** [comment]
Tech팀이 Applications 1차 리뷰 결과물을 리뷰합니다

**Comment by bik1111** [comment]
#5 #11 부분 2차 리뷰 하였습니다 :)

**Comment by 11mLLM** [comment]
리뷰 2차 완료 ✅
