### ISSUE TITLE
Models

### ISSUE THREAD

**Issue by 11mLLM** [11mLLM/Prompt-Engineering-Guide#25]
[1차 리뷰 결과물](https://github.com/11mLLM/11mLLM/issues/4) << Click !

## ☑️ Checklist

1. 의미 왜곡이 없으며 원문의 핵심을 포착했는가?
2. 맞춤법과 문법을 준수하는가?
3. 일관성있는 어조인가?
4. 문맥적 오류가 있는가?
5. 합의한 용어를 준수하는가?

**Comment by 11mLLM** [comment]
Models팀이 Tech 1차 리뷰 결과물을 리뷰합니다

**Comment by won81** [comment]
https://github.com/11mLLM/Prompt-Engineering-Guide/pull/12#pullrequestreview-1553188205
리뷰 추가하였습니다.

**Comment by won81** [comment]
https://github.com/11mLLM/Prompt-Engineering-Guide/pull/14#pullrequestreview-1553588770
리뷰 추가하였습니다.

**Comment by letsbe-x** [comment]
> 1차 리뷰, 1차 리뷰반영 PR, 2차 리뷰
- https://github.com/11mLLM/Prompt-Engineering-Guide/pull/14

> 2차 리뷰 반영 PR
- https://github.com/11mLLM/Prompt-Engineering-Guide/pull/38 

반영했습니다.

**Comment by 11mLLM** [comment]
리뷰 2차 완료 ✅
